<a href="https://colab.research.google.com/github/tirtha0809/Machine-Learning/blob/main/LandSlide_ANN_SMOTE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from imblearn.over_sampling import SMOTE
import time

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


##Importing the dataset

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/LANDSLIDE/Merged_World_LandslideData.csv')
df.size

755820

##Taking care of missing value

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.head()

Index  landslide_category  landslide_size  fatality_count  Latitude  \
0  1858.0                 7.0             2.0             0.0     16.92   
1  1141.0                 6.0             2.0             4.0     30.38   
4    55.0                 6.0             1.0             0.0     42.97   
5  4000.0                 6.0             2.0             2.0     37.75   
6  5609.0                 7.0             3.0             0.0     47.27   

   Longitude  temp-2  temp-1  temp-0  maxt-2  ...  avgslope  LC_Type1_mean  \
0      73.59    26.3    26.5    26.2    27.7  ...    27.875       9.000000   
1      78.09    26.7    27.2    25.8    28.1  ...    81.375       9.000000   
4    -124.01    11.8     8.3     7.8    14.7  ...    88.875       1.000000   
5     -25.20    14.0    14.1    15.8    17.0  ...   167.000       7.058824   
6    -122.26    11.4    11.3    10.6    14.8  ...    40.000       6.764706   

   LST_Day_1km_mean  NDVI_mean  NDWI_mean     aspect  elevation  \
0       15585.75010   0.276409   0.076935   85.79104       68.0   
1       15080.14281   0.256626   0.161844  240.09620      828.0   
4       14795.41238   0.490961   0.363601  173.99826       75.0   
5       14609.53463   0.396181   0.306116   89.37942       68.0   
6       14744.06481   0.352804   0.292128  110.89202       40.0   

   precipitation_sum      slope  landslide_trigger  
0        76083.62956  12.437977                1.0  
1        49711.02632   3.715572                1.0  
4        47384.80481  11.947599                1.0  
5        20904.96219  56.214066                1.0  
6        28623.51198  22.222166                1.0  

[5 rows x 114 columns]

In [ ]:
df.size

499092

In [ ]:
x = df.iloc[:,1:-1].values
y= df.iloc[:,-1].values
smote= SMOTE(k_neighbors = 3)
x_smote,y_smote = smote.fit_resample(x,y)

In [ ]:
print(len(y))

4378


In [ ]:
print(x)

[[7.00000000e+00 2.00000000e+00 0.00000000e+00 ... 6.80000000e+01
  7.60836296e+04 1.24379770e+01]
 [6.00000000e+00 2.00000000e+00 4.00000000e+00 ... 8.28000000e+02
  4.97110263e+04 3.71557240e+00]
 [6.00000000e+00 1.00000000e+00 0.00000000e+00 ... 7.50000000e+01
  4.73848048e+04 1.19475990e+01]
 ...
 [1.00000000e+00 3.00000000e+00 0.00000000e+00 ... 4.36000000e+02
  4.15912462e+04 2.72809580e+01]
 [7.00000000e+00 3.00000000e+00 0.00000000e+00 ... 2.35000000e+02
  3.16836293e+04 1.38575620e+01]
 [6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.40000000e+01
  8.18185791e+04 8.16955600e+00]]


In [ ]:
print(y)

[ 1.  1.  1. ... 15. 15. 15.]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_smote,y_smote,test_size = 0.33,random_state=0)

In [ ]:
print(x_train)

[[6.00000000e+00 2.00000000e+00 3.03200034e+00 ... 3.26079980e+02
  7.54185452e+04 2.00218182e+01]
 [6.72388947e+00 2.27611053e+00 0.00000000e+00 ... 2.56955579e+02
  4.94345672e+04 1.22241187e+01]
 [6.91264395e+00 2.73793186e+00 1.34942418e+00 ... 1.34850407e+02
  5.94536659e+04 1.55561137e+01]
 ...
 [6.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.90943878e+03
  1.03266706e+05 1.71851088e+01]
 [2.49125706e+00 2.00000000e+00 0.00000000e+00 ... 2.69283515e+02
  4.43385524e+04 2.08071910e+01]
 [7.00000000e+00 2.00000000e+00 0.00000000e+00 ... 1.00500000e+03
  1.31981817e+04 4.84394500e+00]]


In [ ]:
print(x_test)

[[1.00000000e+01 2.00000000e+00 0.00000000e+00 ... 6.11000000e+02
  6.58619721e+04 1.68027000e+01]
 [6.27184194e+00 2.00000000e+00 5.70868070e+00 ... 6.25950746e+02
  4.29460532e+04 1.31410312e+01]
 [9.88960512e+00 2.96320171e+00 0.00000000e+00 ... 2.29473810e+02
  2.42869024e+04 2.54396883e+01]
 ...
 [6.71607243e+00 2.14821730e+00 2.13571027e+00 ... 2.53776179e+02
  5.99468060e+04 1.58552118e+01]
 [6.35670278e+00 2.35670278e+00 3.56702784e-01 ... 1.17431867e+03
  6.85124605e+04 2.35512006e+01]
 [1.00000000e+00 2.00000000e+00 0.00000000e+00 ... 8.13000000e+02
  2.15984626e+04 2.19791560e+01]]


In [ ]:
print(y_train)

[13.  5.  7. ...  5.  6. 10.]


In [ ]:
print(y_test)

[ 2.  7. 11. ...  7.  7. 12.]


## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [ ]:
print(x_train)

[[-0.44675564 -0.51082298  0.22176256 ... -0.43169331  1.11013931
   0.3960939 ]
 [ 0.15466974  0.08763756 -0.21120096 ... -0.55310158  0.14413612
  -0.41653508]
 [ 0.31149167  1.08862018 -0.01850592 ... -0.76756387  0.51661493
  -0.06929476]
 ...
 [-0.44675564 -0.51082298 -0.21120096 ...  2.34927617  2.145447
   0.10046924]
 [-3.36190656 -0.51082298 -0.21120096 ... -0.53144912 -0.04531781
   0.47794069]
 [ 0.38406924 -0.51082298 -0.21120096 ...  0.76074384 -1.20301958
  -1.18565204]]


In [ ]:
print(x_test)

[[ 2.87654388 -0.51082298 -0.21120096 ...  0.06873267  0.75485575
   0.06061691]
 [-0.22090259 -0.51082298  0.6039871  ...  0.09499176 -0.09708658
  -0.32098001]
 [ 2.78482506  1.57688519 -0.21120096 ... -0.60136983 -0.79077556
   0.96071148]
 ...
 [ 0.14817516 -0.18956685  0.09377415 ... -0.5586858   0.53494834
  -0.03812456]
 [-0.15039809  0.26231862 -0.16026453 ...  1.05813067  0.85339263
   0.76390474]
 [-4.60088003 -0.51082298 -0.21120096 ...  0.42352012 -0.89072336
   0.60007578]]


In [ ]:
unique_labels = np.unique(y_train)
print(unique_labels)


[ 1.  2.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [ ]:
# Assuming you have 14 unique classes
num_classes = 14

# Ensure class labels are within the valid range [0, num_classes-1]
y_train_corrected = np.clip(y_train, 0, num_classes - 1)

# Convert target labels to one-hot encoded format
y_train_encoded = tf.keras.utils.to_categorical(y_train_corrected, num_classes=num_classes)


## Building an ANN


### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=num_classes,activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy',metrics=['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(x_train,y_train_encoded, batch_size =128, epochs =250)

Epoch 1/250
164/164 [==============================] - 2s 4ms/step - loss: 2.5609 - accuracy: 0.1546
Epoch 2/250
164/164 [==============================] - 0s 2ms/step - loss: 2.3204 - accuracy: 0.2839
Epoch 3/250
164/164 [==============================] - 0s 2ms/step - loss: 2.0748 - accuracy: 0.3523
Epoch 4/250
164/164 [==============================] - 0s 2ms/step - loss: 1.9099 - accuracy: 0.3714
Epoch 5/250
164/164 [==============================] - 0s 2ms/step - loss: 1.8188 - accuracy: 0.3876
Epoch 6/250
164/164 [==============================] - 0s 2ms/step - loss: 1.7569 - accuracy: 0.4018
Epoch 7/250
164/164 [==============================] - 0s 2ms/step - loss: 1.7043 - accuracy: 0.4114
Epoch 8/250
164/164 [==============================] - 0s 2ms/step - loss: 1.6548 - accuracy: 0.4292
Epoch 9/250
164/164 [==============================] - 0s 2ms/step - loss: 1.6055 - accuracy: 0.4476
Epoch 10/250
164/164 [==============================] - 0s 2ms/step - loss: 1.5636 - accura

###predict


In [ ]:
# Ensure class labels in y_test are within the valid range [0, num_classes-1]
y_test_corrected = np.clip(y_test, 0, num_classes - 1)

# Convert y_test to one-hot encoded format
y_test_encoded = tf.keras.utils.to_categorical(y_test_corrected, num_classes=num_classes)

y_pred = ann.predict(x_test)
# Print the concatenated array
concatenated_array = np.concatenate((y_pred, y_test_encoded), axis=1)
np.set_printoptions(precision=2, suppress=True)  # Set formatting options
print(concatenated_array)


322/322 [==============================] - 1s 1ms/step
[[0.   0.42 0.11 ... 0.   0.   0.  ]
 [0.   0.01 0.   ... 0.   0.   0.  ]
 [0.   0.   0.01 ... 1.   0.   0.  ]
 ...
 [0.   0.01 0.   ... 0.   0.   0.  ]
 [0.   0.02 0.   ... 0.   0.   0.  ]
 [0.   0.   0.   ... 0.   1.   0.  ]]


##Making the Confusion Matrix

In [ ]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

mse = mean_squared_error(y_test_encoded, y_pred)
mae = mean_absolute_error(y_test_encoded, y_pred)
r2 = r2_score(y_test_encoded, y_pred)

print("Mean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("R-squared:", r2)


Mean Squared Error: 0.03224468
Mean Absolute Error: 0.0644878
R-squared: 0.45788996236976026
